### ISSUE TITLE
Open source license 

### ISSUE THREAD

**Issue by nellepierson** [dcfemtech/hackforgood-waba-map#120] opened 2016-09-02 12:16 UTC
Decide which open source license we use!

**Comment by alulsh** [comment] 2016-09-02 15:04
Dupe of https://github.com/dcfemtech/hackforgood-waba-map/issues/52, going to close #52 in favor of this one.

Once we decide on a license we should add it to the civic.json file in #53 too.

**Comment by alulsh** [comment] 2016-09-02 15:05
Whoops, thought you could assign an issue to 2 milestones at once, but apparently not 😅 .

**Comment by nellepierson** [comment] 2016-09-02 15:16
deal! thx


*Nelle Pierson *| *Deputy Director *
*Washington Area Bicyclist Association*
2599 Ontario Rd NW Washington DC, 20009
Desk: 202-518-0524 x 202
Cell: 848-863-9442

Your membership results in better bike rides. Click here
<http://www.waba.org/get-involved/become-a-member/>to join or renew your
WABA membership.

**Comment by alongthepike** [comment] 2016-09-04 04:59
My preference is for something simple and permissive, ideally [MIT](https://opensource.org/licenses/MIT) or maybe [Apache](https://opensource.org/licenses/Apache-2.0).

[http://choosealicense.com/](http://choosealicense.com/) may be helpful.

**Comment by alulsh** [comment] 2016-09-06 17:24
Per phone call with @nellepierson we're going to go with an MIT license - as @alongthepike mentioned, it's simple and permissive and should hopefully allow other people to easily re-use our work for bike infrastructure advocacy in other cities.

**Comment by alulsh** [comment] 2016-09-06 17:50
Closed with https://github.com/dcfemtech/hackforgood-waba-map/pull/133.

**Closed by alulsh** 2016-09-06 17:50 UTC
Labels: priority
